version: "3.4"
services:
  backend:
    container_name: ${NAME_BACKEND}
    build:
      context: ./backend/
      dockerfile: "Dockerfile"
    restart: always
    image: ${DOCKER_HUB}/${NAME_BACKEND}:${IMAGE_TAG}
    ports:
      - "8080:80"
    environment:
      - DOCKER_HUB=${DOCKER_HUB}
      - IMAGE_TAG=${IMAGE_TAG:-1.0.0}
      - NAME_BACKEND=${NAME_BACKEND}

  frontend:
    container_name: ${NAME_FRONTEND}
    build:
      context: ./frontend/
      dockerfile: "Dockerfile"
    restart: always
    image: ${DOCKER_HUB}/${NAME_FRONTEND}:${IMAGE_TAG}
    ports:
      - "80:80"
    environment:
      - DOCKER_HUB=${DOCKER_HUB}
      - IMAGE_TAG=${IMAGE_TAG:-1.0.0}
      - NAME_FRONTEND=${NAME_FRONTEND}
