sonar.projectKey=onlineshop
sonar.projectName=onlineshop
sonar.sourceEncoding=UTF-8

sonar.sources=frontend,backend

sonar.exclusions=\
**/*.zip,\
**/*.sql,\
**/node_modules/**,\
**/bin/**,\
**/obj/**,\
**/dist/**,\
**/build/**,\
**/coverage/**

sonar.host.url=https://sonarqube.vun720.dpdns.org/